### PR TITLE
🔒 M-01 - Prevent Replay Attacks by Enforcing Signature Malleability Check

### PR DESCRIPTION
**Pull request by Aboudjem**
#### M-01. Potential Replay Attack Vulnerability in Signature Verification Logic

- **Issue**: Signature malleability due to lack of checks on the `s` value.
- **Affected Functions**: Signature verification logic.
- **Fix**: Add check to ensure `s` value is greater than `0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0`.

### CODE REVIEW

**Comment by livingrockrises** [comment]
Hang on.. in any case we should probably use oz ECDSA library directly instead of making s checks in our code.

**Comment by VGabriel45** [comment]
> Hang on.. in any case we should probably use oz ECDSA library directly instead of making s checks in our code.

It uses the same logic as in the OZ ECDSA library, the signature with the lower 's' value is considered valid. 
If we only need this check I think using the OZ ECDSA library will just increase the code size even more.

**Comment by Aboudjem** [comment]
> > Hang on.. in any case we should probably use oz ECDSA library directly instead of making s checks in our code.
> 
> It uses the same logic as in the OZ ECDSA library, the signature with the lower 's' value is considered valid. If we only need this check I think using the OZ ECDSA library will just increase the code size even more. @livingrockrises @Aboudjem

I agree with the code size concerns, that's something that will need to fix after the remediations.

But Libraries works in a way that it will extend the code size only for the used functions, so it will not add the whole library codesize

**Comment by livingrockrises** [comment]
Yeah you aren't inheriting really so it's not a codesize thing..
anyway I confirmed with spearbit auditors that this is not an issue so I am going to cancel this PR

**Pull request closed without merging**
