### PR TITLE
feat: add hook emergency uninstall

### PR DESCRIPTION
**Pull request by kopy-kat**
please refer to description and comments on
https://github.com/bcnmy/nexus/pull/150

### CODE REVIEW

**Comment by livingrockrises** [comment]
@kopy-kat do you have implementation of the hook that will be used for resource locking?
we want to start building a multiplexer which will sit with this.

**Comment by kopy-kat** [comment]
no, we havent started prototyping the resource lock hook yet. We do have an audited hook multiplexer tho: https://github.com/rhinestonewtf/core-modules/blob/main/src/HookMultiPlexer/HookMultiPlexer.sol

**Review by livingrockrises — APPROVED** [review]

**Comment by livingrockrises** [comment]
ready to merge post spearbit review

**Comment by livingrockrises** [comment]
can just merge now and will inform.

**Pull request merged**
