### PR TITLE
update executeUserOp implementation

### PR DESCRIPTION
**Pull request by livingrockrises**
msgSender field that the hook sees
one major upside of delegatecalling to the account only is that existing hooks will be more easily compatible

eg a spending limit hook will decode the execute calldata and check for the function signature but in the case of using the executeUserOp func on nexus the calldata could be address(erc20), transfer(...) in which case hooks also need to be able to decode this
If you instead have the account delegatecall to eg execute, then the hook can just decode normally

there are no real downsides to delegatecall here

### CODE REVIEW

**Review by VGabriel45 — APPROVED** [review]

**Review by filmakarov — APPROVED** [review]
Agree, that delegatecall'ing here is better

**Review by filmakarov — COMMENTED** [review]
I have a question. Can we limit `execute` to be `onlyEntryPoint` , not `onlyEntryPointOrSelf`  ?
Now when  `executeUserOp` doesn't call `execute` , I think we can do it
This will make execute safer for using with SmartSessions

**Comment by livingrockrises** [comment]
> I have a question. Can we limit `execute` to be `onlyEntryPoint` , not `onlyEntryPointOrSelf` ? Now when `executeUserOp` doesn't call `execute` , I think we can do it This will make execute safer for using with SmartSessions

executeUserOp can now delegate call to self with any calldata actually

btw these below methods are also onlyEntryPointOrSelf

1. installModule
2. uninstallModule
3. setRegistry
4. upgradeToAndCall
5. _authorizeUpgrade
6. withdrawDepositTo

**Comment by filmakarov** [comment]
> executeUserOp can now delegate call to self with any calldata actually

yep, which is good. 
I mean, since it can delegatecall now, can we make `execute` to be `onlyEntryPoint` ?
It will make execute->execute impossible. so the flow is more deterministic.
otherwise it will be possible to trick user to create some execute->execute permission and bypass some limits with sessions

so I suggest `execute` to be `onlyEntryPoint`

**Comment by livingrockrises** [comment]
what do you mean by making execute-> execute impossible? and need for that

**Pull request merged**
