### PR TITLE
Allow Compilation without via-ir

### PR DESCRIPTION
**Pull request by ankurdubey521**
# Coverage with via-ir enabled
## Foundry
Screenshot 2024-08-29 at 2 09 37 PM

## Hardhat
Screenshot 2024-08-29 at 2 10 02 PM

# Coverage with via-ir disabled
## Foundry
Screenshot 2024-08-29 at 2 11 39 PM

## Hardhat
Screenshot 2024-08-29 at 2 10 41 PM

Significant Improvements in the coverage reported by Foundry can be observed, but interestingly, the results from hardhat are unchanged. I don't know why this is the case, perhaps the hardhat handles it differently.

### CODE REVIEW

**Comment by VGabriel45** [comment]
Nice job.
We should exclude scripts and test folder from foundry coverage. I think hardhat coverage is so low because hardhat tests need improvement to cover more code, we have more foundry tests than hardhat tests. For example, registry is not tested at all with hardhat.

**Comment by ankurdubey521** [comment]
fwiw, I believe scripts should also be tested and hence be included in the coverage. see: https://book.getfoundry.sh/tutorials/best-practices?highlight=testing%20scripts#scripts

**Comment by ankurdubey521** [comment]
what benefit do we get by repeating the same tests in hardhat? I believe only the test which can be written in hardhat (testing against client-side or server-side code) should be written in hardhat, for rest we should just default to foundry

**Comment by ankurdubey521** [comment]
Also, there's a section in the coverage report generation script that removes test, mocks and other deps:
```
# Exclude test, mock, and node_modules folders
EXCLUDE="*test* *mocks* *node_modules* *scripts* *lib*"
lcov --rc lcov_branch_coverage=1 --ignore-errors unused --ignore-errors inconsistent --remove lcov.info $EXCLUDE --output-file coverage/foundry/forge-pruned-lcov.info```

**Comment by Aboudjem** [comment]
> Nice job. We should exclude scripts and test folder from foundry coverage. I think hardhat coverage is so low because hardhat tests need improvement to cover more code, we have more foundry tests than hardhat tests. For example, registry is not tested at all with hardhat.

it's removed and give you the actual real coverage when you do `yarn run coverage:report`

**Review by livingrockrises — APPROVED** [review]
LGTM. just tellme how many sloc changes with a commit hash would be helpful to scope this in

**Comment by ankurdubey521** [comment]
> LGTM. just tellme how many sloc changes with a commit hash would be helpful to scope this in

@Aboudjem is there a tool/GitHub integration that can report this number?

**Comment by livingrockrises** [comment]
I am opening one PR with 0.8.27
can maybe close this one then.

also, linting diffs would confuse auditors for PR diff view and scoping.

**Comment by livingrockrises** [comment]
https://github.com/bcnmy/nexus/pull/159

**Pull request closed without merging**
