### PR TITLE
calltype check in fallback flow

### PR DESCRIPTION
**Pull request by livingrockrises**
https://cantina.xyz/code/d1d4b139-9705-4367-9468-297b7078674e/findings/17

do check review comment as well.

### CODE REVIEW

**Review by VGabriel45 — APPROVED** [review]

**Comment by Aboudjem** [comment]
also similar to codehaws #214

**Comment by livingrockrises** [comment]
> Do you plan to add tests here, or should I do it?

go ahead

**Comment by livingrockrises** [comment]
wait till other PR is merged. or I will move this code to other one. 
Can make list of pending tests to be written
@Aboudjem

**Comment by livingrockrises** [comment]
moving this to other PR

**Pull request closed without merging**
